"""Add Book table

Revision ID: 100867ca58e7
Revises: f4a7c0b0d923
Create Date: 2025-05-01 12:21:47.218337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100867ca58e7'
down_revision = 'f4a7c0b0d923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('publicationyear', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Book')
    # ### end Alembic commands ###
