"""empty message

Revision ID: f4a7c0b0d923
Revises: 
Create Date: 2025-05-01 12:12:04.725219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a7c0b0d923'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data1', sa.String(), nullable=True),
    sa.Column('data2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Test')
    # ### end Alembic commands ###
